<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SharpMUTerm.Core</RootNamespace>
    <AssemblyName>SharpMUTerm.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TelnetNegotiationCore" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
