<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SharpMUTerm.Graphics</RootNamespace>
    <AssemblyName>SharpMUTerm.Graphics</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpMUTerm.Core\SharpMUTerm.Core.csproj" />
  </ItemGroup>

</Project>
