<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>MuClient.Scripting</RootNamespace>
    <AssemblyName>MuClient.Scripting</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MoonSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MuClient.Core\MuClient.Core.csproj" />
  </ItemGroup>

</Project>
